version: "3"
services:
  node:
    image: larjim/kademlialab:latest
    stdin_open: true
    tty: true
    deploy:
      replicas: 5
      #        resources:
      #           limits:
      #              cpus: "0.1"
      #              memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - ./:/root
    command: bash -c "
      /root/main ; sleep infinity
      "

networks:
  kademlia_network:
