@startuml class_general_organisation
allowmixing
package kademlia_d7024e {
    class kademlia_cli

    class kademlia_daemon

    package networking {
        class user_restapi_service
        class internal_grpcapi_service
        class internal_grpcapi_client

        internal_grpcapi_client ..> internal_grpcapi_service : to other nodes    
    }

    package model{
        class bucket {
            AddContact(contact Contact) : void
            GetContactAndCalcDistance(target *KademliaID) : Contact[]
            Len() : int
        }
        class contact {
            CalsDistance(target KademliaID) : void
            Less(otherContact Contact) : bool
            String() : string
        }
        class kademlia_id{
            byte[ID_SIZE]
        }

        class routingtable

        class ip_address{
            byte[4]
        }

        routingtable o- bucket : buckets
        routingtable o- contact : me
        bucket o-- contact : contacts
        contact o-kademlia_id : id
        contact o-left- ip_address : address
    }

    actor user 
    user -> kademlia_cli : uses
    kademlia_cli ..> user_restapi_service
    kademlia_daemon --> user_restapi_service
    kademlia_daemon --> internal_grpcapi_client
    kademlia_daemon --> internal_grpcapi_service
    kademlia_daemon o-- routingtable

}

@enduml
